### ISSUE TITLE
Ghost CMS import

### ISSUE THREAD

**Issue by MaluNoPeleke** [OblikStudio/kirby-exporter#6]
Would it be possible to import the json file of a Ghost CMS export into Kirby with this?

**Comment by yandodov** [comment]
Could you give me an example JSON file so I can give it a look? The [Model class](https://github.com/OblikStudio/kirby-walker/blob/master/src/Walker/Model.php) expects the following format:

```js
{
  site: { ... },
  pages: [ ... ],
  files: [ ... ]
}
```

If you can manage to convert your Ghost CMS JSON to this format, it should work fine.

**Comment by MaluNoPeleke** [comment]
I have sent you an export of my blog via email.

**Comment by yandodov** [comment]
It's possible, but the JSON must be heavily reformatted to match the expected format.

Also, this plugin is more geared towards exporting the content _and then_ importing it. Its main use case is for translation management systems where you export the content, translate it, then import it, without changing the structure.

Sadly, this plugin can't create your entire website (including files) from scratch. Kirby is flexible enough to do this, but you'll need a PHP programmer with some free time on their hands to make a script for you. I'd be glad to help you, but I'm swamped with work. You should reach out in [the Kirby forum](https://forum.getkirby.com/). I'm sure someone will be able to help you out! 🙂

**Comment by MaluNoPeleke** [comment]
Thanks a lot for your investigation and suggestion. I asked this already in the Kirby forum some time ago but it seems as nobody has done it before: https://forum.getkirby.com/t/migrating-from-ghost-cms-to-kirby/21720
Now I have to decide if I should pay someone to do this for me, copy & paste everything manually or just stay with Ghost CMS (or I learn how to do it).
As this is mainly for personal reasons and not for earning money with it I will probably choose option 2 or 3 ;)
